language: node_js
node_js:
- node
script: yarn run test
env:
  global:
  - secure: zszWXSiA1/qIXJ+dbh4iX8QdKyWI28woxaBa0bohmH6Gs8irAV7hFsz3mIDRfgtW8a56ZGmkRL2eN/HQ1zyvvrcZaa2IBQhOfPR+ff33WKoqyI7UdfvI8Y4hNzImmWVg30sRAUqFwLePt3jXDFWItiwBfGW7CE6X608LoadI9Ew6fVCMA3rJ2hmxKWr5h/qIyvBdae+OtI7it4RmTF4uAj4xEyLgxMEC+P5zZyPAsQLufpOJWavH7UZNRFLPNLBJRRVfjAYbPU/WztwxVEtmIjFgFl/puvJTsSd9q2rI6XIOEvJhwUZPzJcWBDLVaRf3qCU+4kal8GgkI9c8oshnnbrQatYN6UiB1IhW7XR+W/ndzvl+XHz/DmzBGkisAK4zbjVlm5iqKuWYeH7OqEjm0KBuG6Q8MilmMB8nTF+ddffhaQDtv0TTSNbQaepmdYsrc657eY5L1IWtCiW1cHQlhjgCoDhIsDfs0WXi+BuPBlftDsqK0o/VWfjNanTQJ1i1e1U9UgO9hftVkY95z0xK+YcHKpvKqdJsq6ocymRFeiJMXM5cvuMCdfNPZYtq4TvVFkU7/rhXxEvIC2TDLnoV0OXp7pElrr63NqSlAWeqWosR5X4NABrGjSG1PzLDHY13YXHzWIB+p0nx3PhNVCqbN29WC2k41B5oOYLMDVwdxvY=
